// seedData.js — EventSphere seed data

export const SEED_USERS = [
  // ── Admin ──────────────────────────────────────────────────────────────────
  {
    id: 'admin-001',
    name: 'Admin User',
    email: 'admin@eventsphere.com',
    password: 'admin123',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=AdminUser',
    createdAt: '2024-01-01T00:00:00.000Z',
  },

  // ── Organizers ─────────────────────────────────────────────────────────────
  {
    id: 'org-001',
    name: 'Priya Mehta',
    email: 'priya@eventsphere.com',
    password: 'org123',
    role: 'organizer',
    isVerified: true,
    walletBalance: 4500,
    city: 'Mumbai',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=PriyaMehta',
    createdAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'org-002',
    name: 'Arjun Sharma',
    email: 'arjun@eventsphere.com',
    password: 'org123',
    role: 'organizer',
    isVerified: true,
    walletBalance: 3200,
    city: 'Bangalore',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=ArjunSharma',
    createdAt: '2024-02-01T00:00:00.000Z',
  },
  {
    id: 'org-003',
    name: 'Kavitha Nair',
    email: 'kavitha@eventsphere.com',
    password: 'org123',
    role: 'organizer',
    isVerified: false,
    walletBalance: 2800,
    city: 'Hyderabad',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=KavithaNair',
    createdAt: '2024-02-15T00:00:00.000Z',
  },

  // ── Attendee ──────────────────────────────────────────────────────────────
  {
    id: 'att-001',
    name: 'Rohit Verma',
    email: 'rohit@eventsphere.com',
    password: 'user123',
    role: 'attendee',
    city: 'Mumbai',
    interests: ['Tech', 'Fitness'],
    wishlist: [],
    bookings: [],
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=RohitVerma',
    createdAt: '2024-03-01T00:00:00.000Z',
  },
];

export const SEED_EVENTS = [
  // ── TECH (4 events) ───────────────────────────────────────────────────────
  {
    id: 'evt-001',
    title: 'Mumbai AI & Machine Learning Summit 2025',
    description:
      'Join India\'s brightest minds for a full-day summit on AI, machine learning, and the future of technology. Featuring keynotes from industry leaders, hands-on workshops, and networking sessions.',
    category: 'Tech',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    date: '2025-08-15',
    time: '09:00',
    venue: 'Bombay Exhibition Centre',
    city: 'Mumbai',
    price: 1299,
    capacity: 500,
    ticketsSold: 324,
    bookingCount: 324,
    status: 'approved',
    trending: 'Hot',
    banner: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    tags: ['AI', 'Machine Learning', 'Technology'],
    createdAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'evt-002',
    title: 'Bangalore Startup Hackathon — Build for Bharat',
    description:
      'A 48-hour hackathon bringing together developers, designers, and entrepreneurs to build innovative solutions for Indian problems. ₹5 lakh prize pool up for grabs.',
    category: 'Tech',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    date: '2025-07-20',
    time: '10:00',
    venue: 'NIMHANS Convention Centre',
    city: 'Bangalore',
    price: 499,
    capacity: 300,
    ticketsSold: 187,
    bookingCount: 187,
    status: 'approved',
    trending: 'Rising',
    banner: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80',
    tags: ['Hackathon', 'Startup', 'Innovation'],
    createdAt: '2025-06-05T00:00:00.000Z',
  },
  {
    id: 'evt-003',
    title: 'Delhi Developer Conference 2025',
    description:
      'India\'s premier developer conference with 50+ sessions on cloud, DevOps, open source, and emerging tech. Workshops by Google, Microsoft, and AWS engineers.',
    category: 'Tech',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    date: '2025-09-10',
    time: '09:30',
    venue: 'Pragati Maidan',
    city: 'Delhi',
    price: 999,
    capacity: 800,
    ticketsSold: 412,
    bookingCount: 412,
    status: 'approved',
    trending: 'Hot',
    banner: 'https://images.unsplash.com/photo-1591453089816-0fbb971b454c?w=800&q=80',
    tags: ['Developer', 'Cloud', 'DevOps'],
    createdAt: '2025-06-10T00:00:00.000Z',
  },
  {
    id: 'evt-004',
    title: 'Pune Cybersecurity Workshop',
    description:
      'Hands-on cybersecurity training covering ethical hacking, penetration testing, and digital forensics. Suitable for beginners and intermediate security professionals.',
    category: 'Tech',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    date: '2025-08-05',
    time: '10:00',
    venue: 'Symbiosis Institute of Technology',
    city: 'Pune',
    price: 799,
    capacity: 150,
    ticketsSold: 89,
    bookingCount: 89,
    status: 'pending',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    tags: ['Cybersecurity', 'Hacking', 'Security'],
    createdAt: '2025-06-15T00:00:00.000Z',
  },

  // ── ART (4 events) ────────────────────────────────────────────────────────
  {
    id: 'evt-005',
    title: 'Mumbai Contemporary Art Exhibition — Rasa',
    description:
      'A celebration of contemporary Indian art featuring 80+ artists exploring the nine rasas through painting, sculpture, and digital installations. A must-visit cultural experience.',
    category: 'Art',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    date: '2025-07-25',
    time: '11:00',
    venue: 'National Gallery of Modern Art',
    city: 'Mumbai',
    price: 599,
    capacity: 400,
    ticketsSold: 256,
    bookingCount: 256,
    status: 'approved',
    trending: 'Rising',
    banner: 'https://images.unsplash.com/photo-1531913764164-f85c52e6e654?w=800&q=80',
    tags: ['Art', 'Exhibition', 'Contemporary'],
    createdAt: '2025-06-08T00:00:00.000Z',
  },
  {
    id: 'evt-006',
    title: 'Hyderabad Classical Music Night — Swar Sandhya',
    description:
      'An enchanting evening of Carnatic and Hindustani classical music performances by renowned artists from across India. Experience the soulful magic of India\'s musical heritage.',
    category: 'Art',
    organizerId: 'org-003',
    organizerName: 'Kavitha Nair',
    date: '2025-08-20',
    time: '18:30',
    venue: 'Ravindra Bharati Auditorium',
    city: 'Hyderabad',
    price: 899,
    capacity: 600,
    ticketsSold: 378,
    bookingCount: 378,
    status: 'approved',
    trending: 'Hot',
    banner: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    tags: ['Music', 'Classical', 'Concert'],
    createdAt: '2025-06-12T00:00:00.000Z',
  },
  {
    id: 'evt-007',
    title: 'Chennai Street Art & Graffiti Fest',
    description:
      'Watch 30 street artists transform the walls of Egmore into a living canvas over three days. Interactive mural workshops, live spray painting, and urban art installations.',
    category: 'Art',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    date: '2025-09-05',
    time: '10:00',
    venue: 'Egmore Art District',
    city: 'Chennai',
    price: 299,
    capacity: 1000,
    ticketsSold: 542,
    bookingCount: 542,
    status: 'approved',
    trending: 'Rising',
    banner: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&q=80',
    tags: ['Street Art', 'Graffiti', 'Festival'],
    createdAt: '2025-06-20T00:00:00.000Z',
  },
  {
    id: 'evt-008',
    title: 'Delhi Photography Masterclass by Raghu Rai',
    description:
      'Learn the art of storytelling through photography in this exclusive one-day masterclass. Covers composition, lighting, portrait, and street photography techniques.',
    category: 'Art',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    date: '2025-07-12',
    time: '09:00',
    venue: 'India Habitat Centre',
    city: 'Delhi',
    price: 2499,
    capacity: 50,
    ticketsSold: 34,
    bookingCount: 34,
    status: 'pending',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&q=80',
    tags: ['Photography', 'Workshop', 'Masterclass'],
    createdAt: '2025-06-25T00:00:00.000Z',
  },

  // ── FITNESS (3 events) ────────────────────────────────────────────────────
  {
    id: 'evt-009',
    title: 'Mumbai Marathon 2025 — Run for a Cause',
    description:
      'Join 10,000 runners for Mumbai\'s biggest charity marathon. Distances: 5K, 10K, and 21K. All proceeds go to the Teach For India foundation. Get fit, make a difference.',
    category: 'Fitness',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    date: '2025-09-21',
    time: '06:00',
    venue: 'Marine Drive',
    city: 'Mumbai',
    price: 699,
    capacity: 10000,
    ticketsSold: 7823,
    bookingCount: 7823,
    status: 'approved',
    trending: 'Hot',
    banner: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80',
    tags: ['Marathon', 'Running', 'Charity'],
    createdAt: '2025-05-20T00:00:00.000Z',
  },
  {
    id: 'evt-010',
    title: 'Bangalore International Yoga Festival',
    description:
      'A week-long celebration of yoga featuring 200+ sessions by world-renowned teachers. Covers Hatha, Vinyasa, Ashtanga, and Kundalini yoga. Open to all levels.',
    category: 'Fitness',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    date: '2025-06-21',
    time: '06:30',
    venue: 'Cubbon Park',
    city: 'Bangalore',
    price: 1499,
    capacity: 2000,
    ticketsSold: 1456,
    bookingCount: 1456,
    status: 'approved',
    trending: 'Rising',
    banner: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&q=80',
    tags: ['Yoga', 'Wellness', 'Festival'],
    createdAt: '2025-05-25T00:00:00.000Z',
  },
  {
    id: 'evt-011',
    title: 'Hyderabad CrossFit Championship',
    description:
      'Compete or spectate at South India\'s biggest CrossFit competition. 500 athletes competing across RX, Scaled, and Masters categories. Food trucks, merchandise, and after-party included.',
    category: 'Fitness',
    organizerId: 'org-003',
    organizerName: 'Kavitha Nair',
    date: '2025-08-10',
    time: '08:00',
    venue: 'GMC Balayogi Athletic Stadium',
    city: 'Hyderabad',
    price: 399,
    capacity: 2000,
    ticketsSold: 1123,
    bookingCount: 1123,
    status: 'approved',
    trending: 'Rising',
    banner: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    tags: ['CrossFit', 'Competition', 'Fitness'],
    createdAt: '2025-06-01T00:00:00.000Z',
  },

  // ── CULTURAL (3 events) ───────────────────────────────────────────────────
  {
    id: 'evt-012',
    title: 'Dilli Haat Heritage Craft Festival',
    description:
      'India\'s biggest traditional craft festival featuring artisans from 29 states. Shop authentic handlooms, pottery, jewelry, and folk art. Live folk music and dance performances daily.',
    category: 'Cultural',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    date: '2025-10-02',
    time: '10:00',
    venue: 'Dilli Haat INA',
    city: 'Delhi',
    price: 199,
    capacity: 5000,
    ticketsSold: 2341,
    bookingCount: 2341,
    status: 'approved',
    trending: 'Rising',
    banner: 'https://images.unsplash.com/photo-1627987863379-06c17b671c3d?w=800&q=80',
    tags: ['Heritage', 'Craft', 'Folk', 'Culture'],
    createdAt: '2025-06-18T00:00:00.000Z',
  },
  {
    id: 'evt-013',
    title: 'Chennai Bharatanatyam Dance Gala',
    description:
      'An evening of spectacular Bharatanatyam performances by Padma awardee dancers. The most prestigious classical dance event of South India. Dress in traditional attire for complimentary entry into the pre-show.',
    category: 'Cultural',
    organizerId: 'org-003',
    organizerName: 'Kavitha Nair',
    date: '2025-08-28',
    time: '17:00',
    venue: 'Music Academy Chennai',
    city: 'Chennai',
    price: 1299,
    capacity: 800,
    ticketsSold: 567,
    bookingCount: 567,
    status: 'approved',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    tags: ['Dance', 'Bharatanatyam', 'Classical', 'Cultural'],
    createdAt: '2025-06-22T00:00:00.000Z',
  },
  {
    id: 'evt-014',
    title: 'Pune Ganesh Utsav Cultural Evening',
    description:
      'Celebrate the spirit of Ganesh Utsav with a grand cultural evening featuring lavani performances, dhol-tasha bands, and traditional Maharashtrian cuisine. A tribute to Pune\'s rich heritage.',
    category: 'Cultural',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    date: '2025-09-03',
    time: '18:00',
    venue: 'Shaniwar Wada Grounds',
    city: 'Pune',
    price: 499,
    capacity: 3000,
    ticketsSold: 1876,
    bookingCount: 1876,
    status: 'changes-requested',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1561144257-e32e8506b0c6?w=800&q=80',
    tags: ['Ganesh', 'Cultural', 'Festival', 'Maharashtra'],
    createdAt: '2025-06-28T00:00:00.000Z',
  },

  // ── COMMUNITY (3 events) ──────────────────────────────────────────────────
  {
    id: 'evt-015',
    title: 'Bangalore Green City Volunteer Drive',
    description:
      'Join 2000+ volunteers to plant 10,000 trees across Bangalore\'s neighborhoods. Includes tree saplings, gloves, and tools. Breakfast and lunch provided. Certificate of participation for all volunteers.',
    category: 'Community',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    date: '2025-07-06',
    time: '07:00',
    venue: 'Lal Bagh Botanical Garden',
    city: 'Bangalore',
    price: 199,
    capacity: 2000,
    ticketsSold: 1678,
    bookingCount: 1678,
    status: 'approved',
    trending: 'Rising',
    banner: 'https://images.unsplash.com/photo-1542601906897-b8c8f8c5cb70?w=800&q=80',
    tags: ['Volunteer', 'Environment', 'Community'],
    createdAt: '2025-06-30T00:00:00.000Z',
  },
  {
    id: 'evt-016',
    title: 'Mumbai Startup Networking Mixer',
    description:
      'Connect with 200+ founders, investors, and startup enthusiasts at Mumbai\'s hottest networking event. Speed networking rounds, pitch sessions, and free-flowing conversations over cocktails.',
    category: 'Community',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    date: '2025-07-18',
    time: '18:00',
    venue: 'WeWork BKC Mumbai',
    city: 'Mumbai',
    price: 599,
    capacity: 250,
    ticketsSold: 198,
    bookingCount: 198,
    status: 'approved',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80',
    tags: ['Networking', 'Startup', 'Community'],
    createdAt: '2025-07-01T00:00:00.000Z',
  },
  {
    id: 'evt-017',
    title: 'Hyderabad Book Fair & Author Meetup',
    description:
      'Meet your favorite Telugu and Hindi authors, attend book signings, panel discussions, and creative writing workshops. 500+ publishers and 10,000+ book titles at special prices.',
    category: 'Community',
    organizerId: 'org-003',
    organizerName: 'Kavitha Nair',
    date: '2025-08-30',
    time: '10:00',
    venue: 'Hitex Exhibition Centre',
    city: 'Hyderabad',
    price: 299,
    capacity: 5000,
    ticketsSold: 2134,
    bookingCount: 2134,
    status: 'pending',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
    tags: ['Books', 'Literature', 'Community'],
    createdAt: '2025-07-05T00:00:00.000Z',
  },

  // ── LIFESTYLE (3 events) ──────────────────────────────────────────────────
  {
    id: 'evt-018',
    title: 'Goa Food & Wine Festival 2025',
    description:
      'Indulge in the finest Goan cuisine paired with award-winning wines and craft spirits. 50 restaurants, live cooking demonstrations by celebrity chefs, and a sunset beach party.',
    category: 'Lifestyle',
    organizerId: 'org-003',
    organizerName: 'Kavitha Nair',
    date: '2025-11-15',
    time: '12:00',
    venue: 'Miramar Beach',
    city: 'Goa',
    price: 2999,
    capacity: 1500,
    ticketsSold: 876,
    bookingCount: 876,
    status: 'approved',
    trending: 'Rising',
    banner: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    tags: ['Food', 'Wine', 'Lifestyle'],
    createdAt: '2025-07-08T00:00:00.000Z',
  },
  {
    id: 'evt-019',
    title: 'Delhi Fashion Week — Emerging Designers Showcase',
    description:
      'Discover the next generation of Indian fashion designers at Delhi\'s most anticipated fashion event. 40 emerging designers, front-row access, and a closing gala dinner.',
    category: 'Lifestyle',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    date: '2025-10-20',
    time: '15:00',
    venue: 'The Grand Hotel New Delhi',
    city: 'Delhi',
    price: 1999,
    capacity: 300,
    ticketsSold: 201,
    bookingCount: 201,
    status: 'rejected',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&q=80',
    tags: ['Fashion', 'Design', 'Lifestyle'],
    createdAt: '2025-07-10T00:00:00.000Z',
  },
  {
    id: 'evt-020',
    title: 'Bangalore Travel Photography Expedition',
    description:
      'A 3-day immersive travel photography expedition to the Nilgiri Hills. Professional photography mentor, luxury camp stay, sunset shoots, and post-processing workshops included.',
    category: 'Lifestyle',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    date: '2025-10-10',
    time: '06:00',
    venue: 'Ooty, Nilgiris',
    city: 'Chennai',
    price: 2999,
    capacity: 30,
    ticketsSold: 18,
    bookingCount: 18,
    status: 'changes-requested',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    tags: ['Photography', 'Travel', 'Lifestyle'],
    createdAt: '2025-07-12T00:00:00.000Z',
  },

  // ── Extra rejected event ───────────────────────────────────────────────────
  {
    id: 'evt-021',
    title: 'Kolkata Durga Puja Cultural Night',
    description:
      'Experience the grandeur of Durga Puja with a special cultural performance night featuring Rabindra Sangeet, folk dances, and traditional Bengali cuisine. A tribute to Bengal\'s cultural heritage.',
    category: 'Cultural',
    organizerId: 'org-003',
    organizerName: 'Kavitha Nair',
    date: '2025-10-01',
    time: '17:00',
    venue: 'Netaji Indoor Stadium',
    city: 'Kolkata',
    price: 799,
    capacity: 4000,
    ticketsSold: 0,
    bookingCount: 0,
    status: 'rejected',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1606920586741-09e66b2b94e1?w=800&q=80',
    tags: ['Durga Puja', 'Cultural', 'Bengal'],
    createdAt: '2025-07-15T00:00:00.000Z',
  },

  // ── Extra pending event ───────────────────────────────────────────────────
  {
    id: 'evt-022',
    title: 'Mumbai Blockchain & Web3 Conference',
    description:
      'Dive deep into DeFi, NFTs, DAOs, and the future of decentralized finance. Featuring presentations from top blockchain developers and crypto investors from across Asia.',
    category: 'Tech',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    date: '2025-09-25',
    time: '09:00',
    venue: 'World Trade Centre Mumbai',
    city: 'Mumbai',
    price: 1499,
    capacity: 600,
    ticketsSold: 0,
    bookingCount: 0,
    status: 'pending',
    trending: 'Steady',
    banner: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80',
    tags: ['Blockchain', 'Web3', 'Crypto'],
    createdAt: '2025-07-18T00:00:00.000Z',
  },
];

// 5 bookings for att-001 with correct fee splits
export const SEED_BOOKINGS = [
  {
    id: 'bkg-001',
    eventId: 'evt-001',
    eventTitle: 'Mumbai AI & Machine Learning Summit 2025',
    attendeeId: 'att-001',
    attendeeName: 'Rohit Verma',
    ticketQRCode: 'QR-att001-evt001-001',
    bookedAt: '2025-06-10T10:00:00.000Z',
    amountPaid: 1299,
    platformFee: 129.9,
    organizerReceived: 1169.1,
    paymentStatus: 'confirmed',
    organizerId: 'org-001',
  },
  {
    id: 'bkg-002',
    eventId: 'evt-009',
    eventTitle: 'Mumbai Marathon 2025 — Run for a Cause',
    attendeeId: 'att-001',
    attendeeName: 'Rohit Verma',
    ticketQRCode: 'QR-att001-evt009-002',
    bookedAt: '2025-06-12T14:30:00.000Z',
    amountPaid: 699,
    platformFee: 69.9,
    organizerReceived: 629.1,
    paymentStatus: 'confirmed',
    organizerId: 'org-001',
  },
  {
    id: 'bkg-003',
    eventId: 'evt-010',
    eventTitle: 'Bangalore International Yoga Festival',
    attendeeId: 'att-001',
    attendeeName: 'Rohit Verma',
    ticketQRCode: 'QR-att001-evt010-003',
    bookedAt: '2025-06-15T09:00:00.000Z',
    amountPaid: 1499,
    platformFee: 149.9,
    organizerReceived: 1349.1,
    paymentStatus: 'confirmed',
    organizerId: 'org-002',
  },
  {
    id: 'bkg-004',
    eventId: 'evt-002',
    eventTitle: 'Bangalore Startup Hackathon — Build for Bharat',
    attendeeId: 'att-001',
    attendeeName: 'Rohit Verma',
    ticketQRCode: 'QR-att001-evt002-004',
    bookedAt: '2025-06-18T16:00:00.000Z',
    amountPaid: 499,
    platformFee: 49.9,
    organizerReceived: 449.1,
    paymentStatus: 'confirmed',
    organizerId: 'org-002',
  },
  {
    id: 'bkg-005',
    eventId: 'evt-005',
    eventTitle: 'Mumbai Contemporary Art Exhibition — Rasa',
    attendeeId: 'att-001',
    attendeeName: 'Rohit Verma',
    ticketQRCode: 'QR-att001-evt005-005',
    bookedAt: '2025-06-20T11:00:00.000Z',
    amountPaid: 599,
    platformFee: 59.9,
    organizerReceived: 539.1,
    paymentStatus: 'confirmed',
    organizerId: 'org-001',
  },
];

// Total platform fee from seed bookings = 129.9 + 69.9 + 149.9 + 49.9 + 59.9 = 459.5
export const SEED_PLATFORM_REVENUE = 459.5;

export const SEED_SETTLEMENTS = [
  {
    id: 'stl-001',
    organizerId: 'org-001',
    organizerName: 'Priya Mehta',
    amount: 1169.1 + 629.1 + 539.1, // 2337.3
    bookingIds: ['bkg-001', 'bkg-002', 'bkg-005'],
    settledAt: '2025-06-25T00:00:00.000Z',
    status: 'completed',
  },
  {
    id: 'stl-002',
    organizerId: 'org-002',
    organizerName: 'Arjun Sharma',
    amount: 1349.1 + 449.1, // 1798.2
    bookingIds: ['bkg-003', 'bkg-004'],
    settledAt: '2025-06-26T00:00:00.000Z',
    status: 'completed',
  },
  {
    id: 'stl-003',
    organizerId: 'org-003',
    organizerName: 'Kavitha Nair',
    amount: 0,
    bookingIds: [],
    settledAt: '2025-06-27T00:00:00.000Z',
    status: 'pending',
  },
];
